const profileNames = {
  year_issued: 'Год выпуска',
  transmission: 'КПП',
  color: 'Цвет',
  mileage: 'Пробег',
  steering: 'Руль',
  volume: 'Объем',
  condition: 'Состояние',
  is_custom_cleared: 'Растаможен',
  is_document_issued: 'Оформлен',
  location_origin: 'Откуда',
  plate_number: 'Номера',
  date_imported: 'Дата завоза',
  is_exchangeable: 'Вариант обмена',
  fuel_type: 'Двигатель',
  drive_unit: 'Привод',
  body_type: 'Кузов',
  category: 'Категория',
  type_bus: 'Тип',
  type_cargo: 'Тип',
  type_special: 'Тип',
  brand_cargo: 'Марка',
  model_cargo: 'Модель',
  brand: 'Марка',
  model: 'Модель',
  volume_cargo: 'Объем',
  year_cargo: 'Год',
};

export default profileNames;
