export const FETCH_COMPANY_INFO = 'FETCH_COMPANY_INFO';
export const SUCCESS_FETCH_COMPANY_INFO = 'SUCCESS_FETCH_COMPANY_INFO';
export const FAILURE_FETCH_COMPANY_INFO = 'FAILURE_FETCH_COMPANY_INFO';
