export const FETCH_COMPANIES_LIST = 'FETCH_COMPANIES_LIST';
export const SUCCESS_FETCH_COMPANIES_LIST = 'SUCCESS_FETCH_COMPANIES_LIST';
export const FAILURE_FETCH_COMPANIES_LIST = 'FAILURE_FETCH_COMPANIES_LIST';