export const FETCH_SPARE_PARTS_LIST = 'FETCH_SPARE_PARTS_LIST';
export const SUCCESS_SPARE_PARTS_LIST = 'SUCCESS_SPARE_PARTS_LIST';
export const FAILURE_SPARE_PARTS_LIST = 'FAILURE_SPARE_PARTS_LIST';
